# Generated by Django 5.2.8 on 2025-12-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_bank_bank_id_bank_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='branch',
            new_name='bank',
        ),
    ]
