# Generated by Django 5.2.8 on 2025-12-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_branch_branch_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
